targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
#      dart_json_mapper:
#        generate_for:
#          # here should be listed entry point files having 'void main()' function
#          - lib/main.dart
#
#      # This part is needed to tell original reflectable builder to stay away
#      # it overrides default options for reflectable builder to an **empty** set of files
#      reflectable:
#        generate_for:
#          - no/files